"""Add missing columns to tasks table

Revision ID: 002_add_missing_columns
Revises: 001_initial
Create Date: 2026-04-13 18:45:00.000000

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "002_add_missing_columns"
down_revision = "001_initial"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add parent_id column for task hierarchy
    op.add_column(
        "tasks",
        sa.Column("parent_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        "fk_tasks_parent_id",
        "tasks", "tasks",
        ["parent_id"], ["id"],
        ondelete="CASCADE"
    )

    # Change priority from String to Integer (requires dropping and recreating)
    op.execute("ALTER TABLE tasks ALTER COLUMN priority TYPE INTEGER USING (CASE WHEN priority = 'high' THEN 3 WHEN priority = 'medium' THEN 2 WHEN priority = 'low' THEN 1 ELSE 0 END)")
    op.execute("ALTER TABLE tasks ALTER COLUMN priority SET DEFAULT 0")
    op.execute("ALTER TABLE tasks ALTER COLUMN priority DROP NOT NULL")

    # Add due_time column
    op.add_column(
        "tasks",
        sa.Column("due_time", sa.DateTime(), nullable=True)
    )

    # Add location column
    op.add_column(
        "tasks",
        sa.Column("location", sa.Text(), nullable=True)
    )

    # Add reminder_sent column
    op.add_column(
        "tasks",
        sa.Column("reminder_sent", sa.Boolean(), nullable=True, server_default="false")
    )

    # Change description from String to Text
    op.execute("ALTER TABLE tasks ALTER COLUMN description TYPE TEXT")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Revert description change
    op.execute("ALTER TABLE tasks ALTER COLUMN description TYPE VARCHAR")

    # Drop reminder_sent column
    op.drop_column("tasks", "reminder_sent")

    # Drop location column
    op.drop_column("tasks", "location")

    # Drop due_time column
    op.drop_column("tasks", "due_time")

    # Revert priority change from Integer back to String
    op.execute("ALTER TABLE tasks ALTER COLUMN priority TYPE VARCHAR USING (CASE WHEN priority = 3 THEN 'high' WHEN priority = 2 THEN 'medium' WHEN priority = 1 THEN 'low' ELSE NULL END)")

    # Drop parent_id foreign key and column
    op.drop_constraint("fk_tasks_parent_id", "tasks", type_="foreignkey")
    op.drop_column("tasks", "parent_id")
    # ### end Alembic commands ###
